name: Continuous Integration

on:
  push: 
    branches: 
       - main
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Docker to Login
      uses: docker/login-action@v3.4.0
      with:
       username: ${{secrets.DOCKER_USERNAME}}
       password: ${{secrets.DOCKER_PASSWORD}}

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
        

    - name: Build with JAR
      working-directory: ./module-13_DockerizingApp
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./module-13_DockerizingApp
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-and-java-spacegtech-0.0.1-snapshot:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-and-java-spacegtech-0.0.1-snapshot:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-and-java-spacegtech-0.0.1-snapshot:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-and-java-spacegtech-0.0.1-snapshot:latest
     
